name: Firebase Switch Scheduler

on:
  schedule:
    # 05:30 AM IST → OFF → Firebase true
    - cron: "0 0 * * *"

    # 05:30 PM IST → ON → Firebase false
    - cron: "0 12 * * *"

  workflow_dispatch:

jobs:
  switch-control:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Set Firebase Switch
        run: |
          if [ "${{ github.event.schedule }}" = "0 0 * * *" ]; then
            node update-firebase.js true
          elif [ "${{ github.event.schedule }}" = "0 12 * * *" ]; then
            node update-firebase.js false
          else
            echo "Manual run - setting OFF"
            node update-firebase.js true
          fi
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
