name: Firebase Switch Scheduler

on:
  schedule:
    # 5:30 AM IST → Switch1 TRUE
    - cron: "0 0 * * *"

    # 5:30 PM IST → Switch1 FALSE
    - cron: "0 12 * * *"

  workflow_dispatch:

jobs:
  update-switch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Update Firebase
        run: npm run update
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
